
export const Constants = {
  appname: 'AgentHi.Ai',
  continueToSignUp: 'Continue to sign up',
  weWillLogYouIn: 'If you already have an account, we’ll log you in',
  continueUsingMobile: 'Continue with Mobile',
  continueUsingEmail: 'Continue with Email',
  continueUsingGoogle: 'Continue with Google',
  loginUsingEmail: 'Login with Email',
  loginUsingGoogle: 'Login with Google',
  continueUsingGAuth2: 'Continue with G-Auth 2',
  byCreatingAccount: 'By creating an account you are accepting the',
  byContinuing: 'By Continuing you agree to AgentHi.Ai',
  termAndConditions: 'Terms & Conditions',
  continue: 'Continue',
  privacyPolicy: 'Privacy Policy',
  gladToSeeYou: 'Glad to see you!',
  yourSubscriptionHasExpired: 'Your subscription has expired',
  tapHereToRenew: 'Tap here to renew',
  howICanHelp: 'I\'m here to help. How can I assist you today?',
  aboutUs: 'About us',
  save: 'Save',
  addBreak: 'Add Break',
  about: 'About',
  URLS: {
    YoutubePlaylist: 'https://www.youtube.com/channel/UCkETvQOEJ6URFhV8inJTqNw',
    ContactUrl: 'https://agenthi.ai/contact',
    AboutUs: 'https://agenthi.ai/about-us',
    PrivacyPolicy: 'https://agenthi.ai/privacy',
  },
  myNotes: 'My Notes',
  Notifications: 'Notifications',
  UpdateAppointment: 'Update Appointment',
  Notes: 'Notes',
  SmartAssist: 'Smart Assist',
  hello: 'Hello ',
  twin: 'Twin',
  twinHint: '(Twin is an AI assistant designed to help agents analyze smart notes, summarize content, perform intelligent searches, and assist with smart commands)',
  Optional: ' (Optional)',
  aboutOptional: '(Optional but recommended to help clients understand you better)',
  dummyBio: 'John is a skilled lawyer specializing in corporate law and civil litigation, known for strategic solutions, client-focused counsel, and over a decade of legal expertise.',
  areYouSureWantToLogout: 'Are you sure you want to ',
  privacy: 'Privacy',
  softwareVersion: 'Version :',
  subscriptionDetails: 'Subscription Details',
  contact: 'Contact',
  howDoesItWorks: 'How does it work?',
  howDoesItWorks_: 'How It Works – Watch on YouTube',
  logout: 'Logout',
  areYouSureWantToDelete: 'delete?',
  yes: 'Yes',
  no: 'No',
  close: 'Close',
  public: 'Public',
  private: 'Private',
  summary: 'Summary',
  schedules: 'Schedules',
  scheduledOn: '\'s on',
  pleaseSelectDate: 'Please select a date to check ',
  noMeetingsAvailable: 'Oops, looks like no meetings are available',
  noHistoryAvailable: 'Oops, empty history',
  noNoDetailsForQuery: 'Oops, no details found for query',
  noReminderAvailable: 'No Reminder available',
  noNotesAvailable: 'Oops, looks like no notes are available',
  noNotificationsAvailable: 'No new notifications available',
  noNewClient: 'No new client available',
  noClientAvailable: 'No client available, add them before',
  noLatestNoteAvailable: 'No latest notes available',
  noMatchingUserFound: 'No matching client available',
  viewAll: 'View all',
  add: 'Add',
  messages: 'Messages',
  LatestNotes: 'Latest Notes',
  cancel: 'Cancel',
  settings: 'Settings',
  reminders: 'Reminder',
  and: ' and ',
  accept: 'Accept',
  accepted: 'Accepted',
  TermAndConditionUrl: 'https://agenthi.ai/termsofservice',
  PrivacyPolicyUrl: 'https://agenthi.ai/privacy',
  ByAppyouLabs: 'Powered by BitAdd Labs',
  Date: 'Date',
  Time: 'Time',
  Description: 'Description',
  SetReminder: 'Set reminder',
  AllFieldsWarningMessage: 'Please check the necessary fields',
  AppointmentCreated: 'Appointment created and details shared with clients',
  ReminderCreated: 'Reminder created',
  AppointmentDeleted: 'Appointment deleted',
  ClientDeleted: 'Client deleted',
  errorWhileCreatingAppointment: 'Error while creating Appointment',
  errorWhileDeletingAppointment: 'Error while deleting Appointment',
  errorWhileDeletingClient: 'Error while deleting Client',
  errorWhileCreatingReminder: 'Error while creating reminder',
  agentIdError: 'An error occurred. Please try refreshing the page',
  clientCreationSuccessful: 'Client profile successfully created',
  clientUpdateSuccessful: 'Client profile updated created',
  CreateReminder: 'Create a reminder',
  Title: 'Title',
  meetingTitle: 'Meeting Title',
  MeetingUrlCopied: 'Meeting URL copied',
  MeetingSharedSuccessfully: 'Meeting shared successfully',
  errorWhileSharingMeeting: 'Error while sharing meeting',
  noteHere: 'Click here to add note',
  viewNotes: 'View Notes',
  clickToviewNotes: 'Click to view notes',
  searchClient: 'Search Client',
  search: 'Search',
  AvailableSlots: 'Available Slots',
  NoSlotsAvailable: 'No slots available',
  From: 'From',
  To: 'To',
  MeetingType: 'Meeting type',
  PersonToPerson: 'Person to Person',
  Online: 'Online',
  CreateNewMeeting: 'Create new meeting',
  CreateNewReminder: 'Create new reminder',
  createANew: 'Create a new',
  client: 'Client',
  Appointment: 'Appointment',
  Reminder: 'Reminder',
  CreateClient: 'Create \nClient',
  CreateAppointment: 'Create \nAppointment',
  CreateReminder_: 'Create \nReminder',
  other: 'Other',
  editProfile: 'Edit Profile',
  Editreminders: 'Update Reminders',
  addClient: 'Add Client',
  EditClient: 'Edit Client Details',
  myProfile: 'My Profile',
  firstName: 'First name',
  clientName: 'Client name',
  displayName: 'Display name',
  profileDetails: 'Profile details',
  calenderDetails: 'Calendar details',
  QuickAction: 'Quick Action',
  AskAnything: 'Ask Anything',
  AskAnythingDetail: 'Ask Anything Detail',
  Calender: 'My Calendar',
  lastName: 'Last name',
  AvailableDates: 'Available dates',
  availability: 'Availability',
  EachDayHours: 'Each day hours',
  Exception: 'Exception',
  mobileNo: 'Mobile number',
  updateAvailability: 'Update Availability',
  updateUnavailability: 'Update Unavailability',
  mobile: 'Mobile Number',
  hoursPerDay:`Hour's per day`,
  countryCode:'Country code',
  email:'Email',
  occupation:'Occupation',
  attachments:'Attachments',
  Certificates:'Certificates',
  time_zone:'Timezone',
  supportedDocuments:'supported Documents',
  uploadBtnText: 'Upload using Camera or Gallery',
  takePhoto: 'Take Photo',
  chooseFromGallery: 'Choose from Gallery',
  invalidFileFormat: 'Invalid file format. Please upload a valid image file.',
  OTPFailed: 'OTP verification failed. Please try again or request a new OTP.',
  
  Secrets:{
    GoogleWebClientId:'532380161200-lbhb9ofkdbk8m513o0jvrcninsgi8ien.apps.googleusercontent.com',
    AndroidClientId:'1:532380161200:android:1607a15647684c24cdd775'
  },

  AgentBaseUrl:'http://44.210.108.191:3000/api/agents',
  ClientBaseUrl:'http://44.210.108.191:3000/api/clients',
  TwinBaseUrl:'http://44.210.108.191:3000/api/atwin',
  ApiBaseUrl:'http://44.210.108.191:3000/api/',
  AppointmentBaseUrl:'http://api.test.agenthi.ai:3000/api/appointments',
  ReminderBaseUrl:'http://api.test.agenthi.ai:3000/api/reminders',
  AndroidRedirectionUrlOauth:'com.agenthi.ai.android:/oauthredirect'
};
